# Generated by Django 4.1.3 on 2022-12-10 15:41

from django.db import migrations, models
import system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='receipt_no',
            field=models.CharField(default=system.models.receipt_no_gen, max_length=8, primary_key=True, serialize=False),
        ),
    ]
