# Generated by Django 4.1.3 on 2022-12-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_orderservice_receipt_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'On the way'), (3, 'Ongoing'), (4, 'Done')], default=1),
        ),
    ]
