# Generated by Django 4.1.3 on 2022-12-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_orderservice_paid_orderservice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='payment_method',
            field=models.PositiveIntegerField(choices=[(1, 'Cash'), (2, 'GCash')], default=1),
        ),
    ]
