# Generated by Django 4.1.3 on 2022-12-14 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_orderservice_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='scheduled_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
