# Generated by Django 4.1.3 on 2022-12-15 05:30

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_orderservice_scheduled_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipped',
        ),
        migrations.RemoveField(
            model_name='orderservice',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'On the way'), (3, 'Ongoing'), (4, 'Done')], default=1),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='gcash_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='PH'),
        ),
    ]
