# Generated by Django 4.1.3 on 2022-12-15 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_remove_order_order_status_remove_order_shipped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='total_price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
