# Generated by Django 4.1.3 on 2022-12-23 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_orderservice_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('brgy', models.CharField(max_length=50)),
                ('zip_code', models.PositiveBigIntegerField(default=1234)),
            ],
        ),
        migrations.AddField(
            model_name='orderservice',
            name='billing_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.billinginfo'),
        ),
    ]
