# Generated by Django 4.1.3 on 2023-01-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_billinginfo_orderservice_billing_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_technician',
            field=models.BooleanField(default=False),
        ),
    ]
