# Generated by Django 4.1.3 on 2023-01-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_userprofile_technicianprofile_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_assigned',
        ),
        migrations.AddField(
            model_name='task',
            name='date_finished',
            field=models.DateTimeField(null=True),
        ),
    ]
